### ISSUE TITLE
Support possessive quantifiers

### ISSUE THREAD

**Issue by vlsi** [sgreben/regex-builder#2]
See https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#poss

Possessive quantifiers are important for high-performance regular expressions (see http://www.regular-expressions.info/catastrophic.html).

**Comment by sgreben** [comment]
Great, thanks for the report. As soon as I get to my laptop I'll give this a go - though of course I welcome any contributions.

**Comment by sgreben** [comment]
Done! Added optionalPosessive, manyPossessive, many1Possessive, separatedByPossessive and separatedBy1Posessive.
