### ISSUE TITLE
Library not on Maven

### ISSUE THREAD

**Issue by DieterDePaepe** [sgreben/regex-builder#3]
It seems this library is not present on Maven, despite the description in the README.

https://mvnrepository.com/search?q=com.github.sgreben

**Comment by adrianbadarau** [comment]
@DieterDePaepe Don't know how relevent this is now, but you can use https://jitpack.io/#sgreben/regex-builder/master-188d7b29b1-1 to create your build and load the dependency

**Comment by sgreben** [comment]
Oh no! Let me check what happened there. Thanks for the report, and sorry for the inconvenience @DieterDePaepe

**Comment by sgreben** [comment]
Wow, Dec'17 - no idea how I missed this. Many apologies!

**Comment by sgreben** [comment]
Addressed in 54d40eedc81546d484f97cdfd3c1dbc3976d8e3e, and definitely available [in sonatype/releases now](https://oss.sonatype.org/service/local/repositories/releases/content/com/github/sgreben/regex-builder/1.0.1)

Should also show up in [Maven repo search](https://search.maven.org/search?q=com.github.sgreben) once it picks it up while re-indexing.
