### ISSUE TITLE
Support for named capture groups

### ISSUE THREAD

**Issue by josdejong** [sgreben/regex-builder#7]
Thanks for sharing this library @sgreben, it looks really neat!

Is it possible to give capture groups a name? So that I can generate a regexp like:

```
(?<date>\d{2})-(?<month>\d{2})-(?<year>\d{4})
```

**Comment by sgreben** [comment]
Thanks @josdejong! Currently not, but nothing speaks against adding this (except for dev time constraints :D)

**Comment by josdejong** [comment]
Thanks Sergey. Yeah I feel you regarding the time constraints...

**Comment by sgreben** [comment]
Implemented now. Easier to schedule when already switched into the context :)

**Comment by sgreben** [comment]
NB There's still superfluous non-capturing groups being generated (it is easier to "play it safe" this way), let me know if that's a problem - I'll give minimizing those a go then

**Comment by josdejong** [comment]
Cool, that's very nice! I have to say that in the meantime I've created my own lightweight regex builder, heavily inspired by yours, for the project I'm working on (which required the capture group names and everything).

**Comment by sgreben** [comment]
Cool, is it on github as well? I'd be curious to see how you went about it!

**Comment by josdejong** [comment]
It may be nice to turn it into a public library some day. It's part of a private project, but I can share the code with you in a snippet: 

https://bitbucket.org/teqplay/workspace/snippets/qnMjbz

It's in Kotlin. The comments on top give a brief example and explains the motivations behind it.

**Comment by sgreben** [comment]
Wow, nice! Very clean, I'll steal ideas from that for sure :)

**Comment by josdejong** [comment]
👍 glad you like it. The project we use it in is _very_ heavy on regular expressions, it has hundreds of small and large composed regexps. And the regex builder util functions work like a charm for us, keeping it all readable and maintainable. So thank you for inspiring us to create such a simple, composable API 😄 .
