### ISSUE TITLE
How to create a regex that is case insensitive?

### ISSUE THREAD

**Issue by josdejong** [sgreben/regex-builder#8]
I'm probably overlooking something but I can't figure out how to create a case insensitive regular expression with `regex-builder`. Is this possible?

**Comment by sgreben** [comment]
Just merged #9, which adds a two-argument `Pattern.compile` to which the vanilla j.u.regex flags can be passed, see [the CASE_INSENSITIVE example here](https://github.com/sgreben/regex-builder/search?q=CASE_INSENSITIVE)

**Comment by josdejong** [comment]
👍  Thanks
